apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cryptoapp
  name: cryptoapp
  namespace: cryptoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptoapp
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/injected: enabled
      creationTimestamp: null
      labels:
        app: cryptoapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports: 
        - containerPort: 5000
        env: 
          - name: REACT_APP_RAPIDAPI_KEY
            valueFrom:
              secretKeyRef:
                name: rapidapi-token
                key: api-token
        resources: {}
